baseurl = "http://127.0.0.1"
languageCode = "en-us"
title = "Usman Mahmood"
theme = "hyde"
copyright = "Usman Mahmood"

[Author]
	name = "Usman Mahmood"

[Permalinks]
    blog = "/:year/:month/:filename/"
	
[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Algorithms + Data Structures = Programs"
	github = "https://github.com/umahmood"
